### ISSUE TITLE
Implementing fancy diagnostic messages

### ISSUE THREAD

**Issue by viniciusmuller** [elixir-lang/elixir#12644]
### Elixir and Erlang/OTP versions

Elixir 1.16.0-dev (main branch) (compiled with Erlang/OTP 25)

### Operating system

Any

### Current behavior

Currently there's only the default way of visualizing the errors and warnings outputted by the compiler, this issue aims to settle the design of a new "fancy diagnostics" mode, showing friendlier diagnostics for developers.

### Expected behavior

There are the following cases that I've seen while building an initial draft of it:
- Diagnostics that have `{Line, Column}` as their position and filename information
- Diagnostics that have only `Line` as an integer as their position and filename
- Diagnostics that don't have a filename (`nofile`) (code evaluated/quoted from a string, etc...)

About the current draft implementation:
- By default will always read the source file and showcase/highlight the offending line if the file is readable (i.e: is not `nofile`)
- Will draw an arrow and highlight the offending token if provided with column information
- If the line information is known but the column is unknown, highlight the entire line and provide the message below it

Here's a preview for the following cases:

- Error with `{line, column}` information:
![image](https://github.com/elixir-lang/elixir/assets/59743220/c9f5cb8c-93e5-42bc-ac69-c055f9be2aa4)

- Error with only line information
![image](https://github.com/elixir-lang/elixir/assets/59743220/71875b38-240e-4820-939b-8acd9a8da4ef)

- Warnings with `{line, column}` information: 
![image](https://github.com/elixir-lang/elixir/assets/59743220/77c53f82-02eb-499b-9913-94168ea6d90f)

- Warnings with only line information
![image](https://github.com/elixir-lang/elixir/assets/59743220/fb112b82-4923-4fcc-99b4-bdb4fef078c1)

- Diagnostics without file information

  As the time of writing the fancy diagnostics formatter does not support diagnostics where `file` is not readable.
  We should discuss about this one, but since we don't have much information about the offending code I think we can just render the error message inside the box, such as:
  
  ```
      ┌─ warning: nofile:12
      │
   42 │ Mix.Config.config/2 is deprecated. Use the Config module instead
      │ 
  ```

## References
- [Compiler Errors for Humans - Elm](https://elm-lang.org/news/compiler-errors-for-humans)

## TODO

  * [x] Convert tokenmissing/syntaxerror to new diagnostics
  * [x] Convert group warnings to new diagnostics
  * [x] Convert remaining diagnostics
  * [x] Add precise marking to certain warnings (such as unused variables)
  * [ ] Add column information to undefined local function call
  * [ ] Fix column information to undefined remote function call
  * [ ] Add span to undefined remote function call

**Comment by josevalim** [comment]
This looks great! Since Elixir v1.15 unified warnings and errors, in theory we only need to sketch one of them (and the other comes from free).

I think you already covered the three basic scenarios:
 
1. with line+column
2. with line
3. without snippet or line

There are some additional scenarios and complexities to consider:

1. Some warnings group multiple lines at once. For example, if you call the same deprecated functions several times, we show the warning once and then all locations. The same for undefined functions. How would this look like? Perhaps we should move the warning location to the bottom?

2. If we go down this route we should also unify `SyntaxError` and `TokenMissingError` scenarios (plus #12128). How would those look like? You can try `[1, 2}` and `1 +* 2` as sample snippets.

3. Warnings can be emitted at compile-time or runtime. If at runtime, we don't want them to be fancy because it may slow things down. So functions like `Code.print_diagnostic/1` will need an option to control if the output is fancy or not.

**Comment by viniciusmuller** [comment]
> 1. Some warnings group multiple lines at once. For example, if you call the same deprecated functions several times, we show the warning once and then all locations. The same for undefined functions. How would this look like? Perhaps we should move the warning location to the bottom?

Yes, I think this case will need some special formatting, currently the grouped locations come to us as a string directly, but perhaps we could warn on the first occasion and add further occurrences to the bottom of the warning, something like this:

```
   ┌─ warning: lib/warn_test.ex:4
   │
 4 │ Foo.bar()
   │ ~~~~~~~~
   │
   │ Foo.bar/0 is undefined (module Foo is not available or is yet to be defined)
   │
   │ Invalid call found at 3 other locations:
   |    lib/warn_test.ex:6: WarnTest.a/0
   |    lib/warn_test.ex:7: WarnTest.a/0
   |    lib/warn_test.ex:8: WarnTest.a/0
```

>  2. If we go down this route we should also unify `SyntaxError` and `TokenMissingError` scenarios (plus [Improve mismatched delimiter error message #12128](https://github.com/elixir-lang/elixir/issues/12128)). How would those look like? You can try `[1, 2}` and `1 +* 2` as sample snippets.

Those errors appear to contain the necessary information (line and file) already but use a custom formatter, perhaps we can make them emit error diagnostics for these parsing/lexing errors using the functions from elixir_error? We might need to do some work to bring the line with us when our file is `nofile`, though. Something like this for the SyntaxError case, maybe?

```
   ┌─ error: lib/warn_test.ex:1:6
   │
 1 │ [1, 3}
   │      ╰── Syntax error: unexpected token
   │
```


> 3. Warnings can be emitted at compile-time or runtime. If at runtime, we don't want them to be fancy because it may slow things down. So functions like `Code.print_diagnostic/1` will need an option to control if the output is fancy or not.

No problem, we can add that!

**Comment by josevalim** [comment]
> Those errors appear to contain the necessary information (line and file) already but use a custom formatter, perhaps we can make them emit error diagnostics for these parsing/lexing errors using the functions from elixir_error?

For now, I would prefer to have them share the formatting, rather than make them emit diagnostics (diagnostics fail with CompileError and we cannot change the behaviour here).

---

I am slightly worried about long error messages. For example, the "test": example could happen in a code like this:

    Hello.world(this, is, a, very, long, argument, with: 1 + 2, "keywords": true)

If we follow your style, then all message will be indented on the right. Maybe we should always show the error message in the same position for now (i.e. at the bottom)? Then in the future we can extend. For example, Rust seems to have a specific message that is attached to the snippet which is a summary. Perhaps we can add that in the future?

**Comment by viniciusmuller** [comment]
> I am slightly worried about long error messages. For example, the "test": example could happen in a code like this:

I see your point, in this case we could either:
- Put the text on the left of the arrow
- Always put the error below and use both `^^^` and `~~~` on the "error" to highlight the in the line where the error is (very similar to Elm does in the linked reference)

I think we can go with the latter, what do you think?

> For now, I would prefer to have them share the formatting, rather than make them emit diagnostics (diagnostics fail with CompileError and we cannot change the behaviour here).

That makes sense, we can use the new error/warning formatting functions there and make the diagnostics also use the same code, then.

**Comment by josevalim** [comment]
> I think we can go with the latter, what do you think?

Agreed. Although I wonder that, if we have no column, which one is best:

1. HIghlighting the whole line
2. No highlight whatsoever

I am thinking the first but this should be easy to change later.

**Comment by viniciusmuller** [comment]
I'm currently tackling the syntax error and missing token exceptions, this is how they currently look like:

```
** (SyntaxError)
   ┌─ error: warn.exs:4:6
   │
 4 │ [1, 3}
   │      ^
   │
   │ unexpected token: }
   │
   │ HINT: the "[" on line 4 is missing terminator "]"
   │
    (elixir 1.16.0-dev) src/elixir_errors.erl:509: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:1432: Code.require_file/2
```

Currently they are just formatting the exception, message but in this case I think we can drop the default exception template when fancy, not sure we need the `** (SyntaxError)` or to display the stacktrace when only compiler internals will be shown.

So I'm trying to figure out how we can use a custom format changing the current Exception module code the least possible.

WDYT of this format @josevalim?

**Comment by josevalim** [comment]
It is a bit tricky. The `** (SyntaxError)` is everywhere by default and I wouldn't want to special case it. Similar to the stacktrace, we can remove the `:elixir_errors` entry, but the error can also come from `Code.string_to_quoted!` called by the user, and in such cases we don't want to discard it.

Ideally we would attach some prelude to the syntax error message. For example:


```
** (SyntaxError) unexpected token: }
   ┌─ error: warn.exs:4:6
   │
 4 │ [1, 3}
   │      ^
   │
   │ HINT: the "[" on line 4 is missing terminator "]"
   │
    (elixir 1.16.0-dev) src/elixir_errors.erl:509: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:1432: Code.require_file/2
```

But then we are changing the position of the error message. Another option is to have a dud:


```
** (SyntaxError) invalid syntax found on warn.exs:4:6

   ┌─ error: warn.exs:4:6
   │
 4 │ [1, 3}
   │      ^
   |
   | unexpected token: }
   │
   │ HINT: the "[" on line 4 is missing terminator "]"
   │

    (elixir 1.16.0-dev) src/elixir_errors.erl:509: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:1432: Code.require_file/2
```

**Comment by viniciusmuller** [comment]
I like the latter format! I've implemented the fancy formatting for both SyntaxError and TokenMissingError exceptions, currently they are looking like this:

- SyntaxError with snippet:
```
** (SyntaxError) invalid syntax found on warn.exs:15:9:

    ┌─ error: warn.exs:15:9
    │
 15 │ {1, 3, 5]
    │         ^
    │
    │ unexpected token: ]
    │
    │     HINT: the "{" on line 15 is missing terminator "}"
    │
    │

    (elixir 1.16.0-dev) src/elixir_errors.erl:511: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:1432: Code.require_file/2
```

- TokenMissingError with snippet:
```
** (TokenMissingError) token missing on nofile:1:17:

   ┌─ error: nofile:1:17
   │
 1 │ defmodule Foo do
   │                 ^
   │
   │ missing terminator: end (for "do" starting at line 1)
   │

    (elixir 1.16.0-dev) src/elixir_errors.erl:511: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:542: Code.validated_eval_string/3

```

- TokenMissingError without snippet (fallsback to no-line [due to EOF issues](https://github.com/elixir-lang/elixir/issues/11460))
```
** (TokenMissingError) token missing on warn.exs:16:1:

    ┌─ error: warn.exs:16
    │
 16 │ missing terminator: end (for "do" starting at line 15)
    │

    (elixir 1.16.0-dev) src/elixir_errors.erl:511: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:1432: Code.require_file/2

```

**Comment by josevalim** [comment]
Those all look great except this one:

```
TokenMissingError without snippet (fallsback to no-line https://github.com/elixir-lang/elixir/issues/11460)

** (TokenMissingError) token missing on warn.exs:16:1:

    ┌─ error: warn.exs:16
    │
 16 │ missing terminator: end (for "do" starting at line 15)
    │

    (elixir 1.16.0-dev) src/elixir_errors.erl:511: :elixir_errors.raise/3
    (elixir 1.16.0-dev) lib/code.ex:1432: Code.require_file/2
```

it feels like the "missing terminator: end (for ...)" bit is the code snippet. What if we take the error message out of the code snippet? So we show this:


```
   ┌─ warning: warn.exs:6
   │
 6 │ Foo.bar()
   │ ~~~~~~~~~

   Foo.bar/0 is undefined or private
   Invalid call also found at 3 other locations:
     warn.exs:11: Foo.p/0
     warn.exs:12: Foo.p/0
     warn.exs:13: Foo.p/0
```

and if there is no snippet, we show:

```
   ── error: warn.exs:6
   Foo.bar/0 is undefined or private
   Invalid call also found at 3 other locations:
     warn.exs:11: Foo.p/0
     warn.exs:12: Foo.p/0
     warn.exs:13: Foo.p/0
```

?

**Comment by viniciusmuller** [comment]
> it feels like the "missing terminator: end (for ...)" bit is the code snippet. What if we take the error message out of the code snippet? So we show this:

I'll implement it and share how it looks like!

> One of the benefits of taking the error message out of the | is also that we don't need to do padding for multiline error message.

I agree with that, I've already bumped into a few edge cases when writing the "\n -> pipe separator" code

**Comment by viniciusmuller** [comment]
Nice! By convert to new diagnostics you mean converting the styling? Or do you mean that we are going to emit an error diagnostic in the syntax/missingtoken cases now?

**Comment by josevalim** [comment]
Just the styling, this is the PR #12670.

**Comment by josevalim** [comment]
@viniciusmuller btw, I have one small nitpick:

```
$ elixir -e "1 +* 2"
** (SyntaxError) invalid syntax found on nofile:1:4:
   ┌─ error: nofile:1:4
   │
 1 │ 1 +* 2
   │    ^
   │
   syntax error before: '*'

    (elixir 1.16.0-dev) lib/code.ex:542: Code.validated_eval_string/3
```

Does it feel weird to have the snippet come before the stacktrace? Should we prefix the number with two spaces for when we have a single digit?

**Comment by viniciusmuller** [comment]
Do you mean having something like
```
$ elixir -e "1 +* 2"
** (SyntaxError) invalid syntax found on nofile:1:4:
     ┌─ error: nofile:1:4
     │
   1 │ 1 +* 2
     │    ^
     │
     syntax error before: '*'

    (elixir 1.16.0-dev) lib/code.ex:542: Code.validated_eval_string/3
```

and keep padding it so that if we have errors in bigger line numbers it still stays aligned like this?

```
$ elixir -e "1 +* 2"
** (SyntaxError) invalid syntax found on nofile:1:4:
      ┌─ error: nofile:1:4
      │
   13 │ 1 +* 2
      │    ^
      │
     syntax error before: '*'

    (elixir 1.16.0-dev) lib/code.ex:542: Code.validated_eval_string/3
```

**Comment by josevalim** [comment]
No, I mean only single digit lines. They should be printed as if they were two digits. :)

**Comment by viniciusmuller** [comment]
Oh, I see. Thanks for clarifying, I've opened https://github.com/elixir-lang/elixir/pull/12709 to fix it.

**Comment by viniciusmuller** [comment]
@josevalim currently when showing diagnostics with only the stacktrace, we cannot assume that the first entry will always be the user code location, and thus we don't print it.

Currently code such as `IO.warn :foobar`, without passing an env or keyword list  will give the following output

```
 ┌─ warning
 foobar
  (elixir 1.16.0-dev) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
  (elixir 1.16.0-dev) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
  (elixir 1.16.0-dev) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.16.0-dev) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
```

We don't have much information here, and I think the first thing we can do is to add a newline between the message and the stacktrace, as we do in the other cases.

I'm not sure if we should format the stacktrace differently or have a different format for this specific case, since it makes code more complex and the output less consistent. WDYT?

**Comment by josevalim** [comment]
I think the newline will make it worse, unfortunately, because they won't appear related. One option would be to do this:

```elixir
 ┌─ warning
 foobar
 Stacktrace:
  (elixir 1.16.0-dev) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
  (elixir 1.16.0-dev) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
  (elixir 1.16.0-dev) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.16.0-dev) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
```

But still meh.

Another option is to show as today:

```elixir
warning: foobar
  (elixir 1.16.0-dev) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
  (elixir 1.16.0-dev) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
  (elixir 1.16.0-dev) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.16.0-dev) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
```

But then we start having multiple formats... unless we want to change all messages to be more like:

```
   ┌─ nofile:1:4
   │
 1 │ 1 +* 2
   │    ^
   │
   warning: syntax error before: '*'
```

And then when there is no snippet it feels more natural.

**Comment by viniciusmuller** [comment]
I think the idea of changing the format is nice. The cases where we have the box drawing characters would still look great.

The only special logic I think we would need to inform is to have location to print like this when we have location
```
┌─ <location>
warning: message
``` 

and if there's no location we print it like your example, without the box drawing character and more similar to the old format. WDYT?

**Comment by josevalim** [comment]
If we are going to change the message, what if we try to keep it in the most consistent style as possible:

```
warning: message
    |
 1  |  ...snippet...
    |       ^
    |
    └─ file:line
```

And for the stacktraces:

```
warning: foobar
  (elixir 1.16.0-dev) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
  (elixir 1.16.0-dev) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
  (elixir 1.16.0-dev) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.16.0-dev) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
  (elixir 1.16.0-dev) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
```

This has two wins:

1. Very similar change to the format we have today

2. The location and stacktrace are very similar and always placed in the same area

WDYT?

**Comment by viniciusmuller** [comment]
That seems nice! And the location-but-no-snippet case would stay the same?

**Comment by josevalim** [comment]
Sounds good to me! Please PR :)

**Comment by viniciusmuller** [comment]
Hey @josevalim, I've started implementing this but I think there's a single but tricky problem about having the message in the top: 

Currently we settled on putting the message outside the ascii box and at the bottom because we can easily handle cases where the message is too long and wraps or the message itself contains many lines.

Although I think it makes more sense to have the message at the top and the location at the bottom, I'm not sure how we can have this while handling this case. Any ideas?

As an example of a message with many lines, there's this one from the tests:

```
    ┌─ warning: sample.ex:7: Sample.atom_case/0
    │
  7 │       _ when is_atom(v) -> :ok
    │       ~~~~~~~~~~~~~~~~~~~~~~~~
    │
    incompatible types:

        binary() !~ atom()

    in expression:

        # sample.ex:7
        is_atom(v)

    where "v" was given the type binary() in:

        # sample.ex:4
        v = "bc"

    where "v" was given the type atom() in:

        # sample.ex:7
        is_atom(v)

    Conflict found at
```

**Comment by josevalim** [comment]
I don't see a problem, it would look like this:

```
warning: incompatible types:

    binary() !~ atom()

in expression:

    # sample.ex:7
    is_atom(v)

where "v" was given the type binary() in:

    # sample.ex:4
    v = "bc"

where "v" was given the type atom() in:

    # sample.ex:7
    is_atom(v)

Conflict found at
    │
  7 │       _ when is_atom(v) -> :ok
    │       ~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └ sample.ex:7: Sample.atom_case/0
```

The group warnings is going to be trickier, but we can find something. For example:


```
    │
  7 │       _ when is_atom(v) -> :ok
    │       ~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └ sample.ex:7: Sample.atom_case/0
    └ other_location.ex:7
    └ yet_another_location.ex:7
```

WDYT?

**Comment by viniciusmuller** [comment]
@josevalim I've added some more checkmarks regarding showing spans for unknown function calls, both local and remote.
If you have any pointers on implementing these I would really appreciate it

**Comment by josevalim** [comment]
I think we can go ahead and close this issue itself, since its core has been completed, and then discuss those additions either as new issues (or feel free to email me).

I would start with local function warning, where we need to answer if we highlight only the name, or the name until the parens (which is optional), or the name and all arguments (this last one being very tricky). Perhaps we can look at what Rust does. The remote functions are much harder because we don't have the metadata of the "left side". And generally speaking, the left side of the dot can be any complex expression:

    ("foo" |> String.to_atom()).bar(...)

So maybe starting at the dot is the best way to go for those cases.

Thank you for all amazing contributions!
