### ISSUE TITLE
Could not call defguard check inside defguard.

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir#7147]
### Origin

Talk begins in [Elixir v1.6.0-rc.0 released](https://elixirforum.com/t/elixir-v1-6-0-rc-0-released/11064?u=eiji) news thread.
Here are links for most important posts (from begin to José example):

1. [Original question](https://elixirforum.com/t/elixir-v1-6-0-rc-0-released/11064/7?u=eiji)
2. [Ask again but with old version that uses macros](https://elixirforum.com/t/elixir-v1-6-0-rc-0-released/11064/18?u=eiji)
3. [José Valim response](https://elixirforum.com/t/elixir-v1-6-0-rc-0-released/11064/19?u=eiji)

### Environment

```elixir
$ asdf current
asdf current
elixir ref-v1.6.0-rc.0 (set by /home/eiji/.tool-versions)
erlang 20.2 (set by /home/eiji/.tool-versions)
…
```
Funtoo Linux current x86-64bit on intel64-ivybridge

### Example code from José Valim

```elixir
defmodule Example do
  defguard is_rgb_integer(integer) when integer in 0..255

  defguard is_rgb_strict(rgb)
           when is_rgb_integer(elem(rgb, 0)) and
                  is_rgb_integer(elem(rgb, 1)) and
                  is_rgb_integer(elem(rgb, 2))

  defguard is_css_alpha(alpha) when alpha >= 0 and alpha <= 1
    
  defguard is_rgba(rgba)
           when tuple_size(rgba) == 4 and is_rgb_strict(rgba) and is_css_alpha(elem(rgba, 3))

  defguard is_rgb(rgba)
           when (tuple_size(rgba) == 3 and is_rgb_strict(rgba)) or
                (tuple_size(rgba) == 4 and is_rgb_strict(rgba))
end
```

### Steps to reproduce

0. Ensure you have dependencies for compile sources
1. Install [asdf](https://github.com/asdf-vm/asdf)
2. Add [asdf Erlang plug-in](https://github.com/asdf-vm/asdf-erlang)
3. Install latest available **Erlang** (`asdf list-all erlang` to see all versions)
4. Add [asdf Elixir plug-in](https://github.com/asdf-vm/asdf-elixir)
5. Set **Erlang** version
5. Install **Elixir** `v1.6.0 RC 0` or `master` (I have checked both):
6. Copy example code to at least one of them:
a) `iex` session
b) `lib/example.ex` in new **Elixir** project (`mix new example`)
7. Require `Example` module (`require Example`)
8. Try to call `Example.is_rgb/1` or `Example.is_rgba/1` guard checks

### Reproduce script:

```bash
# File: "reproduce.sh"

#!/bin/bash

# asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.0

# Erlang
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf install erlang 20.2
asdf global erlang 20.2

# Elixir
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
asdf install elixir ref:v1.6.0-rc.0
asdf global elixir ref-v1.6.0-rc.0
# or:
# asdf install elixir ref:master

# Create example project
mix new example
cd example

# Add José Valim code:
cat >lib/example.ex <<EOL
defmodule Example do
  defguard is_rgb_integer(integer) when integer in 0..255

  defguard is_rgb_strict(rgb)
           when is_rgb_integer(elem(rgb, 0)) and
                  is_rgb_integer(elem(rgb, 1)) and
                  is_rgb_integer(elem(rgb, 2))

  defguard is_css_alpha(alpha) when alpha >= 0 and alpha <= 1
    
  defguard is_rgba(rgba)
           when tuple_size(rgba) == 4 and is_rgb_strict(rgba) and is_css_alpha(elem(rgba, 3))

  defguard is_rgb(rgba)
           when (tuple_size(rgba) == 3 and is_rgb_strict(rgba)) or
                (tuple_size(rgba) == 4 and is_rgb_strict(rgba))
end
EOL

# Add extra file for calling guards:
mkdir lib/example
cat >lib/example/sample.ex <<EOL
require Example

# should return false:
Example.is_rgb({255, 255})

# should return true
Example.is_rgb({255, 255, 255})
EOL

# Finally compile project
mix compile
```

**Note**: Reproduce script does not contain any solution for step 0.
**Note 2**: It will not work if you have `example` directory in current working directory

### Current behavior

When compiling (last script line) I got:
```elixir
== Compilation error in file lib/example/sample.ex ==
** (CompileError) lib/example/sample.ex:3: undefined function is_rgb_strict/1
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.and/2
```

### Expected behavior

Code should compile.

### TODO

Based on José Valim response:
> Can you please open up a bug report? I am almost sure we have a test case for this, so I need to investigate exactly what is happening here.

* [x] 1. Check why current tests does not fails
* [x] 2. Add tests for remote calls
* [x] 3. Find and fix issue with call guards in guards (`defguard` and `defguardp`)

cc @christhekeele and @josevalim

**Comment by josevalim** [comment]
Thanks, I can reproduce it. We were not testing remote calls in the suite.

**Comment by Eiji7** [comment]
@josevalim: I found that now elixir compiler generates incorrect warning:

File `reproduce.sh` is enough - just need to change git ref from `tag` to `branch` i.e. from:
```bash
asdf install elixir ref:v1.6.0-rc.0
asdf global elixir ref-v1.6.0-rc.0
```
to:
```bash
asdf install elixir ref:v1.6
asdf global elixir ref-v1.6
```
Then you should see something warning like:
```elixir
warning: this expression will fail with ArgumentError
  lib/example/sample.ex:3
```
which is incorrect, because guards **should not raise** with `ArgumentError`

**Comment by josevalim** [comment]
The warning is correct. :) You are calling is_rgb *outside* of a guard, which means it does fail, especially because you haven't surrounded it by `is_tuple` checks.
