### ISSUE TITLE
doctest checklist

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/elixir#935]
- [x]  If the doctest contains invalid syntax, the tests do not even compile. We should create a failure on runtime and not on compilation time. (@yrashk)
- [x] import: false by default (#931, @yrashk)
- [x] improve ExpectationError — either `expectation - result - instead` or (may be?) a keyword of whatever length, so you can do `[{"expected", a},{"to equal to",b},{"instead", c},{"and also", d}]` ? (@josevalim & @yrashk)
- [x] The doctest is not shown when the exception expected by the doctest does not match the actual exception (@yrashk)
