### ISSUE TITLE
Further unify logger and Logger

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#9465]
- [x] Convert usage of `:error_logger` to `:logger`
- [x] Migrate `:console` backend to be defined as a formatter for `logger_std_h` - this will allow to use the same format as Elixir is using for other handlers as well (requires erlang/otp#2491 - OTP 24+ and erlang/otp#2523 - OTP 23+)
- [x] Only attach built-in `Logger.Handler` if there will be backends (depends on the above)
- [x] Expose API for module and application level verbosity control (#9793)
- [x] Expose and document all of Erlang built-in logger levels (#9791)
- [x] Add support for passing map as a "message" to the `Logger` macros to allow structured logging (needs to be fully discussed before) (#9797)
- [x] Use `time` field from metadata instead of generating new timestamp (#9772)
- [x] Make `Logger.Formatter` works also as a Erlang's logger formatter for use with Erlang's logger handlers
- [x] Make translators a filter
- [x] Document usage and configuration of Erlang's handlers with Elixir's `Logger` (such as the file handler with rotation)
- [x] Add API to set the global metadata (OTP 24+) (#12413)
- [x] Expose `:logger.add_handlers/1` (with an atom) (#12412)
- [x] Rewrite `capture_log` to use Erlang handlers (#12408)
- [x] Publish and CI [`:logger_backends`](https://github.com/elixir-lang/logger_backends) with elixir: ~> 1.15 (https://hex.pm/packages/logger_backends/1.0.0-rc.0)

**Comment by josevalim** [comment]
Note: don't send PRs for those yet. We will probably wait until the Logger integration stabilizes a bit before going all in.

**Comment by hauleth** [comment]
Issues to track:

- erlang/otp#2444 - accept binaries in entries using format
- erlang/otp#2442 - allow ignoring messages from within the log function (by returning `:ignore`)
- erlang/otp#2491 - allow using binaries in `:logger_formatter` template to simplify integration with Elixir

**Comment by hauleth** [comment]
@josevalim I slowly start working on these, so it would be at least partially ready for 1.11.

**Comment by josevalim** [comment]
Perfect, the earlier the better!

**Comment by hauleth** [comment]
Another one PR to core erlang/otp#2523 - this one is to fully support `:device` option in `logger_std_h`.

**Comment by vans163** [comment]
Can this get tagged on too, https://bugs.erlang.org/browse/ERL-1159.

Basically to not push up the REPL prompt on Logger outputs.

**Comment by josevalim** [comment]
Hi @vans163, because the issue happens in both Erlang and Elixir and are not specific to the integration, it should be rather directly tracked in Erlang issues tracker. Thanks for pointing it out though!

**Comment by hauleth** [comment]
Traditionally in most languages the stdout is buffered and stderr is not, this follow libc "standard". Additionally Elixir's logger use `:user` as a default device instead of `:standard_io` and that can be an issue here. AFAIK the problem is unsolvable in general case as there is no "registry" of all defined `io:device/0`s (any registered process can be a device). And as `:user` writes directly to `0` and is not synchronised in any way to `:standard_io` (I am no IEx expert, but I assume that it uses `:standard_io` not `:user` as a IO device).

**Comment by vans163** [comment]
@hauleth I think this PR https://github.com/erlang/otp/pull/2523#issuecomment-581790305, would allow one to easily set standard_io as the output device in logger?  Probably remedying this?

Then OTP error reports, would still hit that same logger right, and go to standard_io too?

**Comment by hauleth** [comment]
Not really, Erlang (as you have spotted) uses `standard_io` by default, it is Elixir that is using `user`. And as I said, it is not possible to do anything about it. If erlang/otp#2523 will be merged then it will be possible to use the same device for logger and IEx and then it will be synchronised, otherwise there is unfortunately no solution for You. Currently you can try with:

```elixir
config :logger, :console,
  device: :standard_io
```

And check if the error is still there. If not then it is exactly what I have said, and it is not a bug.

**Comment by vans163** [comment]
When I set it to standard_io, I get no output at all.

**Comment by josevalim** [comment]
Hi @hauleth! :wave: This is just a heads up that we are about 45 to 60 days before the release candidate for Elixir v1.11. Therefore, if there is anything you believe should be included in Elixir v1.11, please let us know so we can coordinate it properly. Thank you!

**Comment by josevalim** [comment]
I believe both pending tasks here require Erlang/OTP 23. So I guess we have to wait until Erlang/OTP 23 is the minimum required version? If so, maybe we should merge this with #9603?

**Comment by hauleth** [comment]
@josevalim I didn't have much time to spare to work on remaining 2 issues. I will try to make it a thing in 1.12 after I release `enough` library which is extraction of `logger_olp` form the `kernel`.

**Comment by hauleth** [comment]
IIRC these do not require OTP 23, but the problems can be for example with formatter and "compile" step, which is not present in Erlang's formatters and which is used in Elixir's Logger formatter (to change binary format into something that will be easier to digest later).

**Comment by josevalim** [comment]
@hauleth I see. I guess the first task can be broken in two. One is the formatter and the other is the removal of `:console`. My understanding is that Elixir's console logs to `user` and allows the device to configured but this is only available in Erlang/OTP from 23+, so we can't remove `:console` before - which means we can't do the second task either. Using the Erlang formatter for `:console` could be a nice benefit for re-use though (and we can list it as a task on its own).

**Comment by ymtszw** [comment]
Hi, I'm deeply apreciated on structured logging, and I assume it is introduced in Elixir 1.11 partially.
This is a query for clarifying current status:

* Currently, while using `:console` backend (which we do for our container-based deployments), structured reports are automatically converted to string representations of key-value pairs (e.g. `"foo: 100"`), and it CANNOT be customized by means of custom formatter. Is that right?
* And what is the recent plans around `:console` backend? The above comments read that there's a plan to alter the implementation of stdio loggers.

As a background, we are using `:console` backend and custom JSON formatter to emit logs to containers' stdout, and collecting / forwarding them into JSON-based log consumer service (i.e. AWS CloudWatch).
I'm asking this to know if our current approach still holds in coming Elixir versions.

**Comment by josevalim** [comment]
That’s right. We kept the current format for backwards compatibility. We have plans to have new backends that can handle the structured logging as is. Right now, your best option is to implement an Erlang logger handler.

**Comment by hauleth** [comment]
Yes, currently there is no way to format the reports (structured messages) in **Elixir formatter**, however, you can do it **Elixir translator**. It will require some workarounds to not format everything, but in general should be possible. However as @josevalim said, it would probably be better to implement it as Erlang logger handler. I am working on creating [`enough`](https://github.com/hauleth/enough) library for providing last missing piece from the Erlang logger handler (which is overload protection) if you need something like that.

**Comment by ymtszw** [comment]
Thank you two for the clarification!

Quick search gave me this forum post: https://elixirforum.com/t/how-do-i-use-erlang-flatlog-in-a-mix-project/32697
Regarding to implement our logger handler as Erlang logger handler. Is this still a viable starting point?

Or, for now I should rather try on Elixir translator path?

Either way, my intention is (a) handle structured reports and emit them as JSON objects (if possible right now), while (b) easing the foreseeable migration when stdio logging is rearchitectured.

**Comment by hauleth** [comment]
Whatever works for you. If you do not care, or you will handle all formatting on your own, then I would go with Erlang logger formatter for `logger_std_h`. The only problem there is that you will need to configure your logger in application startup, as Elixir do not support configuring it via `config/config.exs` in development. So you will end with different logger implementations in development and production. If that suits you, then you can go that way. Implementing formatter for Erlang handler is very straightforward and I really encourage you to check that out, as I see it as a great simplification over the Elixir approach.

**Comment by josevalim** [comment]
@hauleth this is the "document". :D I want to see what need to update and tackle. :)

**Comment by hauleth** [comment]
@josevalim I have added few points. Maybe we should split this issue into set of smaller ones that will describe each of the needed tasks, and then join them using GitHub Project instead of having one issue that is "catch'em all".

**Comment by josevalim** [comment]
@hauleth if they are not being acted on, I would prefer to keep them here to avoid "polluting" the issues tracker. We can always fork out when there is a plan to move forward. :)

**Comment by josevalim** [comment]
And thanks for the additions, they look great! :+1:

**Comment by hauleth** [comment]
Added more stuff. Some of them are ready to be done in OTP 24+ (migration from `:console` to `:logger_std_h`) and added links to Erlang issues in few others.

**Comment by Lucasrezzaghi** [comment]
As a beginner contributor, can i help somehow?

**Comment by polvalente** [comment]
@hauleth Me and a colleague noticed that between Elixir 1.12 and Elixir 1.13 a change was introduced in which `Logger.warning` now prints `"[warning]"` instead of `"[warn]"` as the log level metadata. This seemed to be an intentional change, from what the diff between 1.12 and 1.13 shows.

However, I could not find any mention of this in the Elixir 1.13 changelog. Did I miss something too obvious?
This isn't too critical, but this could potentially break monitoring stacks which depend on the log level string.

PS: Sorry if this isn't the proper channel to ask this. Please point me to the proper one if this is the case!

**Comment by hauleth** [comment]
@polvalente it is not my doing, but it sounds like bug, so you probably should create separate issue for that. The formatter output should not change as it may be breaking change (as you have noted).

**Comment by josevalim** [comment]
We changed "warn" output to align with the new log levels and Erlang/OTP. I will update the CHANGELOG.

**Comment by tsloughter** [comment]
Is nested metadata supported by Elixir Logger?

I almost missed this when about to merge https://github.com/open-telemetry/opentelemetry-erlang/pull/394 which uses nested `logger` metadata. In the example using Erlang formatter for the default handler it looks like:

```
 {otel_span_ctx, ["trace_id=", [otel_span_ctx, trace_id], " ",
                            "span_id=", [otel_span_ctx, span_id], " "], []},
```

So it only has to check if `otel_span_ctx` key exists and if it does it includes the trace and span id, if not it includes nothing `[]`.

The metadata looks like:

```
logger:update_process_metadata(#{otel_span_ctx =>  #{trace_id => io_lib:format("~32.16.0b", [TraceId]),
                                                     span_id => io_lib:format("~16.16.0b", [SpanId]),
                                                     trace_flags => case TraceFlags band 1 of 1 -> "01"; _ -> "00" end}}).
```

It was first noticed by @btkostner who didn't see the metadata when using `:all` https://github.com/open-telemetry/opentelemetry-erlang/pull/394#issuecomment-1139085945 but does when using his own Logger backend.

**Comment by Ljzn** [comment]
@tsloughter it looks like the Logger will ignore the metadata value which didn't implement the String.Chars. A simple solution could be
```
defimpl String.Chars, for: Map do
  def to_string(map), do: Jason.encode!(map)
end
```

**Comment by tsloughter** [comment]
@Ljzn yea, but doesn't allow for creating log lines like in Erlang that have `trace_id=... span_id=...`

**Comment by tsloughter** [comment]
@josevalim before I switched to the less efficient form of having each one individual in the metadata, I thought I should check if, assuming hauleth sends a PR, this is something you'd backport? I assume not and don't think we want to require users be on the latest 1.13 patch release if this gets added, so was going to change how we do the metadata to continue supporting 1.11+.

**Comment by josevalim** [comment]
We can add support for nested logger metadata. We just need to come up with a good rule to do it. Supporting maps (except structs)/keyword with only atoms keys can be a good default?

**Comment by tsloughter** [comment]
Could go with a dot based separator to keep the same style template: `"$time trace_id=$otel_span_ctx.trace_id [$level] $message\n"`

@josevalim I don't think you need any rule for the actual metadata -- except for the tyepspec -- just enforce that the template is based on atoms, which if it is parsed from a string like it is now doesn't even require testing user input.

Should just support what the Erlang logger does since they use the same metadata.

**Comment by josevalim** [comment]
@tsloughter love the dot proposal. We can go ahead with it! But it will have to be `$metadata.foo.bar`. PRs are welcome!

**Comment by tsloughter** [comment]
@josevalim great.

I went ahead with flattening nested metadata in Otel. It is only 3 fields, so not the end of the world having to have the formatter do the extra check that a key exists -- and also not worth requiring users to upgrade to 1.13.x or 1.14.

**Comment by hauleth** [comment]
@josevalim I worry that any change to the templating format in current (string) state may be breaking change.

**Comment by josevalim** [comment]
It might be but: 1. it is unlikely and 2. we can warn on a previous version

**Comment by cognivore** [comment]
Is `warn` \ `warning` change the reason for this weird bug:  https://gist.github.com/wkirschbaum/39bd31aebc7af0f0fcc001c4b0243591

?

**Comment by yordis** [comment]
Before I forget so we can track the feature. @hauleth maybe would be prudent to add to the task lists "Add Erlang single_line logger config to Elixir Logger package"

Related to: https://groups.google.com/g/elixir-lang-core/c/-zzJUZS2JtI

**Comment by yordis** [comment]
@josevalim I added https://github.com/elixir-lang/elixir/issues/9465#issuecomment-1407780663 as a note to make sure it was tracked.

Should I create an issue for it?

**Comment by josevalim** [comment]
That's a new feature and not really part of making of the compatibility work. If someone wants to contribute it as a feature, then we will gladly review it, but we don't plan to tackle it ourselves.

**Comment by yordis** [comment]
Got it!

**Comment by michallepicki** [comment]
There was a point here about:

> Do not depend on logger:macro_log (requires https://github.com/erlang/otp/pull/2721 - OTP 24+)

which was removed from the list by @whatyouhide on Feb 17. Can I ask why this was removed and not done? There are still calls to `:logger.macro_log` in the Elixir codebase

**Comment by josevalim** [comment]
We have to handle other formats (like atoms) because of backwards compatibility.  :(
